### PR TITLE
New baseCaptured Zone Module

### PR DESCRIPTION
**Pull request by cloose**
This zone raises a flag when a base (Airbase, FARP, Ship) has been captured by a coalition. I found such a zone quite useful in my missions. So I thought you might be interested in this contribution.

Properties

```
    - baseCaptured       Marks this as baseCaptured zone. The value is ignored. (MANDATORY)
    - baseName           Name for the airdrome, helipad or ship. In case of helipad or ship it's the unit name.
                         If no name is set then the associated captured flag is triggered for all bases.
    - coalition          The coalition that needs to capture the base. Accepts 0/all, 1/red, 2/blue.
      captureCoalition   Defaults to 0 (all)
    - filterFor          Which base categories to look for. Accepts 0/airdrome,1/helipad,2/ship and 3/all.
                         Defaults to 3 (all)
    - method             DML Flag method for output. Use only one synonym per zone.
      capturedMethod     Defaults to "flip".
    - f!                 The flag to bang! after the base matching above filter criteria has been captured.
      captured!          Use only one synonym per zone.
```

### CODE REVIEW

**Review by csofranz — COMMENTED** [review]
That's a great idea, thanks. 

The module could be a little bit more user-friendly - I think it would be better if the zone associated itself with the closest FARP/Shit/Airfield automatically, making it that much easier to use in ME. dcsCommon.getClosestAirbaseTo() can do that with the zone's location automatically (that's how I do it in CivAir), so that's easily covered, and makes the zone easier to use for mission designers. The zone doesn't even have to a linked zone, as the airfield is identified at the mission's beginning, so even if it's moving (ship - can they even be captured? I don't think so), it will still trigger correctly when it is captured

I currently have a more general event-based module (generate flag changes on specific world events) on DML's roadmap, and this could be a nice middle-ground test ground (along with parashoo and object destruct detector).

**Comment by cloose** [comment]
Thanks for the feedback!

I agree that the possibility to automatically assign the closest base to the zone makes it more user-friendly. But it also makes one possible use-case harder to implement: Counting how many bases have been capture by one side.

So I added a configuration attribute "autoAssignClosestBase" to control this behavior. The default is the user-friendly version. I also added another demo mission that shows the above mentioned use-case.

I guess, you are right regarding ships being captured.

**Comment by csofranz** [comment]
> But it also makes one possible use-case harder to implement: Counting how many bases have been capture by one side.

That's a good point, but I'm slightly struggling to understand why this is the case. How are you counting owned bases, and what is your underlying premise that differentiates between assigning from hand, and assigning automatically? Shouldn't they have the same result?

Are we perhaps missing another module? From an engineering standpoint, I want to avoid creating modules for mixed purposes. In the past, I've erred in that direction: the earlier "conquerable zones" are a good, bad example - they mix functionality (ownership and spawning) and I'll have to break them up later and make their functionality orthogonal to better fit with DML. 

The base capture module should be one module with a specific use, and we need figure out how it can best support counting before we close design. Obviously, xFlags is a candidate, but it may indeed require that we rethink both modules, or add another counter module next to countDown. 

How would you implement captured base counting using modules, and what would you need for that to happen? I'm not sure I understand the hand-coded base naming requirement in this context, so I'm probably overlooking something obvious. I want to find the most simple setup that can be universally used. 

Currently I'm thinking about the following idea: imagine a very basic baseCapture module (pretty much as it's now, fully auto-assigned with one addition). It has is two outputs: "captured!" a flag that is banged each time ownership changes. It also has a an output baseOwner, which is set to 0 (neutral), 1 (red), or 2 (blue), depending on the current owner. 

How would we count the number of owned bases? xFlags can count the number of inputs that have a certain value, so if can be used for that purpose to detect a win condition - if the proposed ownership flag exists in baseCapture. It may also be an idea to extend xFlags to provide an xCount output in addition to xDirect. Or to create a separate count module that simply counts the number of input flags that match a certain condition. 

So, I believe that your example is rather highlighting the fact that DML is missing a module (a counter) , rather than a shortcoming in baseCapture itself.

What do you think?

Oh, and another question: for attribution - do you want to be attributed for your work, and if so, how? As 'cloose' or differently?

Cheers,
-ch

**Comment by cloose** [comment]
I see, there are a lot of thoughts going into these modules. 😄  I like it! 👍 

I will try to explain. Currently the counting of "capture events" can be implemented like this:

grafik

This zone is not assigned to any specific base (no baseName attribute provided and autoAssignClosestBase is false). So the flag is incremented if any base is captured by coalition RED.

One can then use the flag as win condition - RED captured x bases - with the watchflag functionality:

grafik

If you assign each basedCaptured zone automatically or by hand to a base, then you would have to create a zone for every base on the map to be able to count the events. Or do I miss something here?

So I see the properties baseName, captureCoalition and filterFor more like filter for which base captured events I want to trigger the flag. Maybe the name of the properties need to be changed to reflect that? filterBaseName, filterCaptureCoalition, filterBaseCategory?

One could of course also add a separate event counter module. But it would be a) very similar in structure and implementation and b) the method property for the flag (like e.g. inc) would make less sense to me.

That's just my point of view. It's your baby 😄 

Thanks to your previous hard work this module was really easy to create. Even for someone without any previous Lua knowledge like me. So the code here is under public domain.  No attribution needed. If you still want to, then 'cloose' is fine.

**Comment by csofranz** [comment]
Ah, I get it! You are counting the capture events. The premise is that, for example, after four capture events for red, red has captured four bases. Unfortunately, merely counting events is dangerous, because it may make assumptions that aren't necessarily true. Here your assumption is probably that the number of conquer events for your side is equal to the number of bases your side has conquered. 

Can we find a disproof? Imaging the following scenario: Base A is owned by blue. Red captures A --> red conquer counter increases. Red loses A to blue again, nothing happens (except perhaps a blue conquer counter increases). Red re-gains control, counter increases. The red capture counter now stands at 2, yet red only owns one base: A. Counting conquer events does not indicate number of bases owned. 

We need to find another way to count owned bases. As a possible approach, I re-submit the idea of a pollable 'owner' flag. Let's think this over, but it feels like we are close to a solution :)

**Comment by csofranz** [comment]
I like this particular module because it may make [this mission](https://forum.dcs.world/topic/289267-catch-keep-integrated-warfare-multi-module-singlemulti-player/#comment-4850553) easier, and more modular. 

When designing a module, we should not assume too much about the later game. The approach with counting capture events does not work because it doesn't cover recaptures. We could try and balance that, by adding a second module that decrements red for each blue capture. 

However, that assumes that we only have two factions. We have three: neutrals, and perhaps later a "green" faction. Balancing counts can't cover that, or the solution gets exponentially more convoluted. The more I think about this issue the more it becomes obvious to me that we need true counting abilities in DML.

**Comment by cloose** [comment]
The "a certain coalition has captured the closest base" is certainly the most important and common use-case.

So yeah, I agree that it probably makes sense to post-pone any decision on other use-cases and start with the simpliest and most useful one. 

I simplified the module and removed the "baseName" and "filterFor" attributes. The zone is now automatically assigned to the closest airbase and the "coalition" attribute controls what coalition has to capture the base in order to bang the flag.

**Comment by cloose** [comment]
Now looking at it. Should the flag be the value of the "baseCaptured" attribute? I mean remove "f!" and "captured!" and change the zone to "baseCaptured!" instead? Similar to "raiseFlag!".

**Pull request merged**
